name: Integração Contínua Projeto WEB 2

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copiar Arquivo .env
        run: cp example.env .env

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Instalar Dependências
        run: |
          npm install 
          npm install -g nodemon

      - name: Iniciar Aplicação com Nodemon
        run: nodemon index.js &

      - name: Executar ESLint
        run: npm run lint

      - name: Rodar Testes
        run: npm run test