name: Integração Contínua

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Instalar Dependências
        run: npm install

      - name: Iniciar Aplicação
        run: npm start &

      - name: Esperar a Inicialização
        run: sleep 10 

      - name: Rodar Testes
        run: npm test 
